/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-03-01
The MIT License (MIT) Copyright (c) 2018 STMicroelectronics
******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include <gpio_cpp.h>

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */



int main(void)
{
  int i = 0;

  while (1)
  {
	i++;
  }
}
