/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-03-01
The MIT License (MIT) Copyright (c) 2018 STMicroelectronics
******************************************************************************
*/

/* Includes */
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "gpio_cpp.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */



int main(void)
{

  RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);

  GPIO_InitTypeDef initStruct;
  initStruct.GPIO_Mode = GPIO_Mode_OUT;
  initStruct.GPIO_OType = GPIO_OType_PP;
  initStruct.GPIO_Pin = GPIO_Pin_13;
  initStruct.GPIO_PuPd = GPIO_PuPd_NOPULL;
  initStruct.GPIO_Speed = GPIO_Speed_100MHz;

  GPIO_Init(GPIOD, &initStruct);

 // GPIO_SetBits(GPIOD, GPIO_Pin_13);

  GPIO gpio;
  volatile int i = 0;

  while (1)
  {
	  gpio.setBit(GPIO_Pin_13);
	  for (i = 0; i < 1000000; ) {
		  i++;

	  }

	  gpio.resetBit(GPIO_Pin_13);
	  for (i = 0; i < 1000000; ) {
		  i++;

	  }
  }
}
