/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-03-01
The MIT License (MIT) Copyright (c) 2018 STMicroelectronics
******************************************************************************
*/

/* Includes */
#include "stm32f4xx_rcc.h"
#include "gpio_cpp.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */


int main(void)
{

  RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);


  myGPIO* gpio = myGPIOD;
  gpio->init(GPIO_Mode::OUT, GPIO_OType::PP, GPIO_PuPd::NOPULL, GPIO_Speed::S_100MHz, GPIO_Pin_13);


  while (1)
  {
	  gpio->toggleBit(GPIO_Pin_13);
  }
}





